def generate_retrofit_plan(address: str, solar_data: dict, incentive_data: dict) -> dict:
    """
    Placeholder for the AI service.
    This will call an LLM (OpenAI or Gemini) to synthesize
    the raw data into a cohesive RetrofitPlan.
    """
    return {
        "summary": "This is a placeholder summary generated by AI.",
        "upgrades": []
    }
